theme: jekyll-theme-minimal
title: Mobilized African Diaspora at Columbia University
description: Here is the centralized place to access our published resources and join us in our actions!
baseurl: /MADwebsite
#email: mad.columbia@gmail.com
#instagram_username: mad.columbia
#twitter-username: MADatCU
#facebook_username: MADatCU
#medium_username: MADatCU

